// client/src/views/seller/AddProduct.jsx
import { useState } from 'react'
import { Link } from 'react-router-dom'

const AddProduct = () => {
  const categories = [
    {
      id: 1,
      name: 'Sports',
    },
    {
      id: 2,
      name: 'Tshirt',
    },
    {
      id: 3,
      name: 'Mobile',
    },
    {
      id: 4,
      name: 'Computer',
    },
    {
      id: 5,
      name: 'Watch',
    },
    {
      id: 6,
      name: 'Pant',
    },
  ]

  const [state, setState] = useState({
    name: '',
    description: '',
    discount: '',
    price: '',
    brand: '',
    stock: '',
  })

  const inputHandle = (e) => {
    setState({
      ...state,
      [e.target.name]: e.target.value,
    })
  }

  const [cateShow, setCateShow] = useState(false)
  const [category, setCategory] = useState('')
  const [allCategory, setAllCategory] = useState(categories)
  const [searchValue, setSearchValue] = useState('')

  const categorySearch = (e) => {
    const value = e.target.value

    setSearchValue(value)

    if (value) {
      let srcValue = allCategory.filter(
        (c) => c.name.toLowerCase().indexOf(value.toLowerCase()) > -1
      )

      setAllCategory(srcValue)
    } else {
      setAllCategory(categories)
    }
  }

  return (
    <div className="px-2 lg:px-7 pt-5">
      <div className="w-full p-4 bg-[#6a5fdf] rounded-md">
        <div className="flex justify-between items-center pb-4">
          <h1 className="text-[#d0d2d6] text-xl font-semibold">Add Product</h1>
          <Link className="bg-blue-500 hover:shadow-blue-500/50 hover:shadow-lg text-white rounded-sm px-7 py-2 my-2">
            All Product
          </Link>
        </div>
        <div>
          <form>
            <div className="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]">
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="name">Product Name</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.name}
                  type="text"
                  name="name"
                  id="name"
                  placeholder="Product Name"
                />
              </div>

              <div className="flex flex-col w-full gap-1">
                <label htmlFor="brand">Product Brand</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.brand}
                  type="text"
                  name="brand"
                  id="brand"
                  placeholder="Brand Name"
                />
              </div>
            </div>
            <div className="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]">
              <div className="flex flex-col w-full gap-1 relative">
                <label htmlFor="category">Category</label>
                <input
                  readOnly
                  onClick={() => setCateShow(!cateShow)}
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={category}
                  type="text"
                  id="category"
                  placeholder="--select category--"
                />

                <div
                  className={`absolute top-[101%] bg-[#475569] w-full transition-all ${
                    cateShow ? 'scale-100' : 'scale-0'
                  } `}
                >
                  <div className="w-full px-4 py-2 fixed">
                    <input
                      value={searchValue}
                      onChange={categorySearch}
                      className="px-3 py-1 w-full focus:border-indigo-500 outline-none bg-transparent border border-slate-700 rounded-md text-[#d0d2d6] overflow-hidden"
                      type="text"
                      placeholder="search"
                    />
                  </div>
                  <div className="pt-14"></div>
                  <div className="flex justify-start items-start flex-col h-[200px] overflow-x-scrool">
                    {allCategory.map((c, i) => (
                      <span
                        key={i}
                        className={`px-4 py-2 hover:bg-indigo-500 hover:text-white hover:shadow-lg w-full cursor-pointer ${
                          category === c.name && 'bg-indigo-500'
                        }`}
                        onClick={() => {
                          setCateShow(false)
                          setCategory(c.name)
                          setSearchValue('')
                          setAllCategory(categories)
                        }}
                      >
                        {c.name}{' '}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="stock">Product Stock</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.stock}
                  type="text"
                  name="stock"
                  id="stock"
                  placeholder="Stock"
                />
              </div>
            </div>
            <div className="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]">
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="price">Price</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.price}
                  type="number"
                  name="price"
                  id="price"
                  placeholder="price"
                />
              </div>
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="discount">Discount</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.discount}
                  type="number"
                  name="discount"
                  id="discount"
                  placeholder="discount by %"
                />
              </div>
            </div>
            <div className="flex flex-col w-full gap-1">
              <label htmlFor="description" className="text-[#d0d2d6]">
                Description
              </label>
              <textarea
                className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                onChange={inputHandle}
                value={state.description}
                name="description"
                id="description"
                placeholder="Description"
                cols="10"
                rows="4"
              ></textarea>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}

export default AddProduct

// client-angular/src/app/views/seller/add-product.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-add-product',
  standalone: true,
  imports: [
    CommonModule,
  ],
  template: `<p>add-product works!</p>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AddProductComponent { }

<div class="px-2 lg:px-7 pt-5">
    <div class="w-full p-4 bg-[#6a5fdf] rounded-md">
        <div class="flex justify-between items-center pb-4">
            <h1 class="text-[#d0d2d6] text-xl font-semibold">Add Product</h1>
            <a
                class="bg-blue-500 hover:shadow-blue-500/50 hover:shadow-lg text-white rounded-sm px-7 py-2 my-2"
                routerLink="/seller/dashboard/products"
                >All Product</a
            >
        </div>
        <div>
            <form [formGroup]="productForm" (ngSubmit)="submit()">
                <div
                    class="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]"
                >
                    <div class="flex flex-col w-full gap-1">
                        <label for="name">Product Name</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            name="name"
                            id="name"
                            placeholder="Product Name"
                            formControlName="name"
                            required
                        />
                    </div>
                    <div class="flex flex-col w-full gap-1">
                        <label for="brand">Product Brand</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            name="brand"
                            id="brand"
                            placeholder="Brand Name"
                            formControlName="brand"
                            required
                        />
                    </div>
                </div>
                <div
                    class="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]"
                >
                    <div class="flex flex-col w-full gap-1 relative">
                        <label for="category">Category</label>
                        <input
                            readOnly
                            (click)="$cateShow.set(!$cateShow())"
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            id="category"
                            placeholder="--select category--"
                            formControlName="category"
                            required
                        />
                        <div
                            class="absolute top-[101%] bg-[#475569] w-full transition-all"
                            [ngClass]="$cateShow() ? 'scale-100' : 'scale-0'"
                        >
                            <div class="w-full px-4 py-2 fixed">
                                <input
                                    [value]="$searchValue()"
                                    (change)="searchValue($event)"
                                    class="px-3 py-1 w-full focus:border-indigo-500 outline-none bg-transparent border border-slate-700 rounded-md text-[#d0d2d6] overflow-hidden"
                                    type="text"
                                    placeholder="search"
                                />
                            </div>
                            <div class="pt-14"></div>
                            <div
                                class="flex justify-start items-start flex-col h-[200px] overflow-x-scrool"
                            >
                                @for (currentCategory of $categories(); track
                                currentCategory._id; let idx = $index) {
                                <span
                                    class="px-4 py-2 hover:bg-indigo-500 hover:text-white hover:shadow-lg w-full cursor-pointer"
                                    [ngClass]="
                                        productForm.controls['category']
                                            .value === currentCategory.name
                                            ? 'bg-indigo-500'
                                            : ''
                                    "
                                    (click)="
                                        $cateShow.set(false);
                                        productForm.controls[
                                            'category'
                                        ].setValue(currentCategory.name);
                                        $searchValue.set('')
                                    "
                                    >{{ currentCategory.name }}</span
                                >
                                }
                            </div>
                        </div>
                    </div>
                    <div class="flex flex-col w-full gap-1">
                        <label for="stock">Product Stock</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            name="stock"
                            id="stock"
                            placeholder="Stock"
                            formControlName="stock"
                            required
                        />
                    </div>
                </div>
                <div
                    class="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]"
                >
                    <div class="flex flex-col w-full gap-1">
                        <label for="price">Price</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="number"
                            name="price"
                            id="price"
                            placeholder="price"
                            formControlName="price"
                            required
                        />
                    </div>
                    <div class="flex flex-col w-full gap-1">
                        <label for="discount">Discount</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="number"
                            name="discount"
                            id="discount"
                            placeholder="discount by %"
                            formControlName="discount"
                            required
                        />
                    </div>
                </div>
                <div class="flex flex-col w-full gap-1 mb-5">
                    <label for="description" class="text-[#d0d2d6]">
                        Description
                    </label>
                    <textarea
                        class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                        name="description"
                        id="description"
                        placeholder="Description"
                        cols="10"
                        rows="4"
                        formControlName="description"
                    ></textarea>
                </div>
            </form>
        </div>
    </div>
</div>
