// client/src/views/seller/EditProduct.jsx
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'

const EditProduct = () => {
  const categories = [
    {
      id: 1,
      name: 'Sports',
    },
    {
      id: 2,
      name: 'Tshirt',
    },
    {
      id: 3,
      name: 'Mobile',
    },
    {
      id: 4,
      name: 'Computer',
    },
    {
      id: 5,
      name: 'Watch',
    },
    {
      id: 6,
      name: 'Pant',
    },
  ]

  const [state, setState] = useState({
    name: '',
    description: '',
    discount: '',
    price: '',
    brand: '',
    stock: '',
  })

  const inputHandle = (e) => {
    setState({
      ...state,
      [e.target.name]: e.target.value,
    })
  }

  const [cateShow, setCateShow] = useState(false)
  const [category, setCategory] = useState('')
  const [allCategory, setAllCategory] = useState(categories)
  const [searchValue, setSearchValue] = useState('')

  const categorySearch = (e) => {
    const value = e.target.value

    setSearchValue(value)

    if (value) {
      let srcValue = allCategory.filter(
        (c) => c.name.toLowerCase().indexOf(value.toLowerCase()) > -1
      )

      setAllCategory(srcValue)
    } else {
      setAllCategory(categories)
    }
  }

  // const [images, setImages] = useState([])
  const [imageShow, setImageShow] = useState([])

  const changeImage = (img, files) => {
    if (files.length > 0) {
      console.log(img)
      console.log(files[0])
    }
  }

  useEffect(() => {
    setState({
      name: 'Mens tshirt',
      description: 'Utilities for controlling how',
      discount: 5,
      price: 255,
      brand: 'Easy',
      stock: 10,
    })

    setCategory('Tshirt')

    setImageShow([
      'http://localhost:5173/src/assets/images/admin.jpg',
      'http://localhost:5173/src/assets/images/demo.jpg',
      'http://localhost:5173/src/assets/images/seller.png',
    ])
  }, [])

  return (
    <div className="px-2 lg:px-7 pt-5">
      <div className="w-full p-4 bg-[#6a5fdf] rounded-md">
        <div className="flex justify-between items-center pb-4">
          <h1 className="text-[#d0d2d6] text-xl font-semibold">Edit Product</h1>
          <Link
            to="/seller/dashboard/products"
            className="bg-blue-500 hover:shadow-blue-500/50 hover:shadow-lg text-white rounded-sm px-7 py-2 my-2"
          >
            All Product
          </Link>
        </div>
        <div>
          <form>
            <div className="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]">
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="name">Product Name</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.name}
                  type="text"
                  name="name"
                  id="name"
                  placeholder="Product Name"
                />
              </div>
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="brand">Product Brand</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.brand}
                  type="text"
                  name="brand"
                  id="brand"
                  placeholder="Brand Name"
                />
              </div>
            </div>
            <div className="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]">
              <div className="flex flex-col w-full gap-1 relative">
                <label htmlFor="category">Category</label>
                <input
                  readOnly
                  onClick={() => setCateShow(!cateShow)}
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={category}
                  type="text"
                  id="category"
                  placeholder="--select category--"
                />

                <div
                  className={`absolute top-[101%] bg-[#475569] w-full transition-all ${
                    cateShow ? 'scale-100' : 'scale-0'
                  } `}
                >
                  <div className="w-full px-4 py-2 fixed">
                    <input
                      value={searchValue}
                      onChange={categorySearch}
                      className="px-3 py-1 w-full focus:border-indigo-500 outline-none bg-transparent border border-slate-700 rounded-md text-[#d0d2d6] overflow-hidden"
                      type="text"
                      placeholder="search"
                    />
                  </div>
                  <div className="pt-14"></div>
                  <div className="flex justify-start items-start flex-col h-[200px] overflow-x-scroll">
                    {allCategory.map((c, i) => (
                      <span
                        key={i}
                        className={`px-4 py-2 hover:bg-indigo-500 hover:text-white hover:shadow-lg w-full cursor-pointer ${
                          category === c.name && 'bg-indigo-500'
                        }`}
                        onClick={() => {
                          setCateShow(false)
                          setCategory(c.name)
                          setSearchValue('')
                          setAllCategory(categories)
                        }}
                      >
                        {c.name}{' '}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="stock">Product Stock</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.stock}
                  type="text"
                  name="stock"
                  id="stock"
                  placeholder="Stock"
                />
              </div>
            </div>
            <div className="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]">
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="price">Price</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.price}
                  type="number"
                  name="price"
                  id="price"
                  placeholder="price"
                />
              </div>
              <div className="flex flex-col w-full gap-1">
                <label htmlFor="discount">Discount</label>
                <input
                  className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                  onChange={inputHandle}
                  value={state.discount}
                  type="number"
                  name="discount"
                  id="discount"
                  placeholder="discount by %"
                />
              </div>
            </div>
            <div className="flex flex-col w-full gap-1 mb-5">
              <label htmlFor="description" className="text-[#d0d2d6]">
                Description
              </label>
              <textarea
                className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                onChange={inputHandle}
                value={state.description}
                name="description"
                id="description"
                placeholder="Description"
                cols="10"
                rows="4"
              ></textarea>
            </div>
            <div className="grid lg:grid-cols-4 grid-cols-1 md:grid-cols-3 sm:grid-cols-2 sm:gap-4 md:gap-4 gap-3 w-full text-[#d0d2d6] mb-4">
              {imageShow.map((img, i) => (
                <div key={i}>
                  <label htmlFor={i}>
                    <img src={img} alt="" />
                  </label>
                  <input
                    onChange={(e) => changeImage(img, e.target.files)}
                    type="file"
                    id={i}
                    className="hidden"
                  />
                </div>
              ))}
            </div>
            <div className="flex">
              <button className="bg-red-500  hover:shadow-red-500/40 hover:shadow-md text-white rounded-md px-7 py-2 my-2">
                Save Changes
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}

export default EditProduct

// client-angular/src/app/views/seller/edit-product.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-edit-product',
  standalone: true,
  imports: [
    CommonModule,
  ],
  template: `<p>edit-product works!</p>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class EditProductComponent { }

<div class="px-2 lg:px-7 pt-5">
    <div class="w-full p-4 bg-[#6a5fdf] rounded-md">
        <div class="flex justify-between items-center pb-4">
            <h1 class="text-[#d0d2d6] text-xl font-semibold">Edit Product</h1>
            <a
                class="bg-blue-500 hover:shadow-blue-500/50 hover:shadow-lg text-white rounded-sm px-7 py-2 my-2"
                routerLink="/seller/dashboard/products"
                >All Product</a
            >
        </div>
        <div>
            <form [formGroup]="productForm" (ngSubmit)="submit()">
                <div
                    class="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]"
                >
                    <div class="flex flex-col w-full gap-1">
                        <label for="name">Product Name</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            name="name"
                            id="name"
                            placeholder="Product Name"
                            formControlName="name"
                            required
                        />
                    </div>
                    <div class="flex flex-col w-full gap-1">
                        <label for="brand">Product Brand</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            name="brand"
                            id="brand"
                            placeholder="Brand Name"
                            formControlName="brand"
                            required
                        />
                    </div>
                </div>
                <div
                    class="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]"
                >
                    <div class="flex flex-col w-full gap-1 relative">
                        <label for="category">Category</label>
                        <input
                            readOnly
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            id="category"
                            placeholder="--select category--"
                            formControlName="category"
                            required
                        />
                        <!-- <div
                            class="absolute top-[101%] bg-[#475569] w-full transition-all"
                            [ngClass]="$cateShow() ? 'scale-100' : 'scale-0'"
                        >
                            <div class="w-full px-4 py-2 fixed">
                                <input
                                    [value]="$searchValue()"
                                    (change)="categorySearch($event)"
                                    class="px-3 py-1 w-full focus:border-indigo-500 outline-none bg-transparent border border-slate-700 rounded-md text-[#d0d2d6] overflow-hidden"
                                    type="text"
                                    placeholder="search"
                                />
                            </div>
                            <div class="pt-14"></div>
                            <div
                                class="flex justify-start items-start flex-col h-[200px] overflow-x-scrool"
                            >
                                @for (currentCategory of $categories(); track
                                currentCategory._id; let idx = $index) {
                                <span
                                    class="px-4 py-2 hover:bg-indigo-500 hover:text-white hover:shadow-lg w-full cursor-pointer"
                                    [ngClass]="
                                        productForm.controls['category']
                                            .value === currentCategory.name
                                            ? 'bg-indigo-500'
                                            : ''
                                    "
                                    (click)="
                                        $cateShow.set(false);
                                        productForm.controls[
                                            'category'
                                        ].setValue(currentCategory.name);
                                        $searchValue.set('')
                                    "
                                    >{{ currentCategory.name }}</span
                                >
                                }
                            </div>
                        </div> -->
                    </div>
                    <div class="flex flex-col w-full gap-1">
                        <label for="stock">Product Stock</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="text"
                            name="stock"
                            id="stock"
                            placeholder="Stock"
                            formControlName="stock"
                            required
                        />
                    </div>
                </div>
                <div
                    class="flex flex-col mb-3 md:flex-row gap-4 w-full text-[#d0d2d6]"
                >
                    <div class="flex flex-col w-full gap-1">
                        <label for="price">Price</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="number"
                            name="price"
                            id="price"
                            placeholder="price"
                            formControlName="price"
                            required
                        />
                    </div>
                    <div class="flex flex-col w-full gap-1">
                        <label for="discount">Discount</label>
                        <input
                            class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                            type="number"
                            name="discount"
                            id="discount"
                            placeholder="discount by %"
                            formControlName="discount"
                            required
                        />
                    </div>
                </div>
                <div class="flex flex-col w-full gap-1 mb-5">
                    <label for="description" class="text-[#d0d2d6]">
                        Description
                    </label>
                    <textarea
                        class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                        name="description"
                        id="description"
                        placeholder="Description"
                        cols="10"
                        rows="4"
                        formControlName="description"
                    ></textarea>
                </div>
                <div
                    class="grid lg:grid-cols-4 grid-cols-1 md:grid-cols-3 sm:grid-cols-2 sm:gap-4 md:gap-4 gap-3 w-full text-[#d0d2d6] mb-4"
                >
                    @for (image of $imageShow(); track image; let idx = $index)
                    {
                    <div class="h-[180px] relative">
                        <label [htmlFor]="idx">
                            <img
                                [src]="image.url"
                                alt=""
                                class="w-full h-full rounded-sm"
                            />
                        </label>
                        <input
                            id="{{ idx }}"
                            type="file"
                            class="hidden"
                            (change)="changeImage(image.url, $event)"
                        />
                    </div>
                    }
                </div>
                <div class="flex">
                    <button
                        class="bg-red-500 w-[280px] hover:shadow-red-300/50 hover:shadow-lg text-white rounded-md px-7 py-2 mb-3"
                    >
                        Save Changes
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
