// client/src/views/seller/Products.jsx
/* eslint-disable react-hooks/exhaustive-deps */

import { useEffect, useState } from 'react'
import { FaEdit, FaEye, FaTrash } from 'react-icons/fa'
import { useDispatch, useSelector } from 'react-redux'
import { Link } from 'react-router-dom'
import { getProducts } from '../../store/reducers/productReducer'
import Search from '../components/Search'
import Pagination from '../Pagination'

const Products = () => {
  const dispatch = useDispatch()

  const { products, totalProduct } = useSelector((state) => state.product)

  const [currentPage, setCurrentPage] = useState(1)
  const [searchValue, setSearchValue] = useState('')
  const [parPage, setParPage] = useState(5)

  useEffect(() => {
    const obj = {
      parPage: parseInt(parPage),
      page: parseInt(currentPage),
      searchValue,
    }

    dispatch(getProducts(obj))
  }, [searchValue, currentPage, parPage])

  return (
    <div className="px-2 lg:px-7 pt-5">
      <h1 className="text-[#000000] font-semibold text-lg mb-3">
        All Products
      </h1>
      <div className="w-full p-4 bg-[#6a5fdf] rounded-md">
        <Search
          setParPage={setParPage}
          setSearchValue={setSearchValue}
          searchValue={searchValue}
        />
        <div className="relative overflow-x-auto mt-5">
          <table className="w-full text-sm text-left text-[#d0d2d6]">
            <thead className="text-sm text-[#d0d2d6] uppercase border-b border-slate-700">
              <tr>
                <th scope="col" className="py-3 px-4">
                  No
                </th>
                <th scope="col" className="py-3 px-4">
                  Image
                </th>
                <th scope="col" className="py-3 px-4">
                  Name
                </th>
                <th scope="col" className="py-3 px-4">
                  Category
                </th>
                <th scope="col" className="py-3 px-4">
                  Brand
                </th>
                <th scope="col" className="py-3 px-4">
                  Price
                </th>
                <th scope="col" className="py-3 px-4">
                  Discount
                </th>
                <th scope="col" className="py-3 px-4">
                  Stock
                </th>
                <th scope="col" className="py-3 px-4">
                  Action
                </th>
              </tr>
            </thead>
            <tbody>
              {products.map((d, i) => (
                <tr key={i}>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    {i + 1}
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    <img
                      className="w-[45px] h-[45px]"
                      src={d.images[0]}
                      alt=""
                    />
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    {d?.name?.slice(0, 15)}...
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    {d.category}
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    {d.brand}{' '}
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    ${d.price}
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    {d.discount === 0 ? (
                      <span>No Discount</span>
                    ) : (
                      <span>%{d.discount}</span>
                    )}
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    {d.stock}
                  </td>
                  <td
                    scope="row"
                    className="py-1 px-4 font-medium whitespace-nowrap"
                  >
                    <div className="flex justify-start items-center gap-4">
                      <Link
                        to={`/seller/dashboard/edit-product/${d._id}`}
                        className="p-[6px] bg-yellow-500 rounded hover:shadow-lg hover:shadow-yellow-500/50"
                      >
                        {' '}
                        <FaEdit />{' '}
                      </Link>
                      <Link className="p-[6px] bg-green-500 rounded hover:shadow-lg hover:shadow-green-500/50">
                        {' '}
                        <FaEye />{' '}
                      </Link>
                      <Link className="p-[6px] bg-red-500 rounded hover:shadow-lg hover:shadow-red-500/50">
                        {' '}
                        <FaTrash />{' '}
                      </Link>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {totalProduct <= parPage ? (
          ''
        ) : (
          <div className="w-full flex justify-end mt-4 bottom-4 right-4">
            <Pagination
              pageNumber={currentPage}
              setPageNumber={setCurrentPage}
              totalItem={50}
              parPage={parPage}
              showItem={3}
            />
          </div>
        )}
      </div>
    </div>
  )
}

export default Products

// client-angular/src/app/views/seller/products.component.ts
import { CommonModule } from '@angular/common'
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  inject,
  Signal,
  signal,
  WritableSignal,
} from '@angular/core'
import { SearchComponent } from '@app/components/search.component'
import { Product } from '@app/models'
import {
  productActions,
  selectProducts,
  selectTotalProducts,
} from '@app/store/product'
import {
  FontAwesomeModule,
  IconDefinition,
} from '@fortawesome/angular-fontawesome'
import {
  faCircleXmark,
  faEye,
  faImage,
  faPenToSquare,
  faTrash,
} from '@fortawesome/free-solid-svg-icons'
import { Store } from '@ngrx/store'
import { PaginationComponent } from '../pagination.component'

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [
    CommonModule,
    FontAwesomeModule,
    SearchComponent,
    PaginationComponent,
  ],
  templateUrl: './products.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductsComponent {
  private readonly _store = inject(Store);

  public $products: Signal<Product[]> =
    this._store.selectSignal(selectProducts);
  public $totalProducts: Signal<number> =
    this._store.selectSignal(selectTotalProducts);

  public $currentPage: WritableSignal<number> = signal(1);
  public $searchValue: WritableSignal<string> = signal('');
  public $parPage: WritableSignal<number> = signal(5);

  public fanPenToSquare: IconDefinition = faPenToSquare;
  public faTrash: IconDefinition = faTrash;
  public faCircleXmark: IconDefinition = faCircleXmark;
  public faImage: IconDefinition = faImage;
  public faEye: IconDefinition = faEye;

  constructor() {
    effect(
      (): void => {
        const obj = {
          parPage: this.$parPage(),
          page: this.$currentPage(),
          searchValue: this.$searchValue(),
        };

        this._store.dispatch(productActions.getProducts({ payload: obj }));
      },
      { allowSignalWrites: true }
    );
  }
}

<div class="px-2 lg:px-7 pt-5">
    <h1 class="text-[#000000] font-semibold text-lg mb-3">All products</h1>
    <div class="w-full p-4 bg-[#6a5fdf] rounded-md">
        <app-search
            [searchValue]="$searchValue()"
            (setSearchValue)="$searchValue.set($event)"
            (setParPage)="$parPage.set($event)"
        ></app-search>
        <div class="relative overflow-x-auto mt-5">
            <table class="w-full text-sm text-left text-[#d0d2d6]">
                <thead
                    class="text-sm text-[#d0d2d6] uppercase border-b border-slate-700"
                >
                    <tr>
                        <th scope="col" class="py-3 px-4">No</th>
                        <th scope="col" class="py-3 px-4">Image</th>
                        <th scope="col" class="py-3 px-4">Name</th>
                        <th scope="col" class="py-3 px-4">Category</th>
                        <th scope="col" class="py-3 px-4">Brand</th>
                        <th scope="col" class="py-3 px-4">Price</th>
                        <th scope="col" class="py-3 px-4">Discount</th>
                        <th scope="col" class="py-3 px-4">Stock</th>
                        <th scope="col" class="py-3 px-4">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @for (product of $products(); track product._id; let idx =
                    $index) {
                    <tr>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            {{ idx + 1 }}
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            <img
                                class="w-[45px] h-[45px]"
                                [src]="product.images[0]"
                                alt=""
                            />
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            {{ product.name.slice(0, 15) }}...
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            {{ product.category }}
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            {{ product.brand }}
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            {{ product.price | currency }}
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            @if (product.discount === 0) {
                            <span>No Discount</span>
                            } @else {
                            <span>%{{ product.discount }}</span>
                            }
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            {{ product.stock }}
                        </td>
                        <td class="py-1 px-4 font-medium whitespace-nowrap">
                            <div class="flex justify-start items-center gap-4">
                                <a
                                    class="p-[6px] bg-yellow-500 rounded hover:shadow-lg hover:shadow-yellow-500/50"
                                >
                                    <fa-icon [icon]="fanPenToSquare"></fa-icon>
                                </a>
                                <a
                                    class="p-[6px] bg-green-500 rounded hover:shadow-lg hover:shadow-green-500/50"
                                >
                                    <fa-icon [icon]="faEye"></fa-icon>
                                </a>
                                <a
                                    class="p-[6px] bg-red-500 rounded hover:shadow-lg hover:shadow-red-500/50"
                                >
                                    <fa-icon [icon]="faTrash"></fa-icon>
                                </a>
                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
        @if ($totalProducts() <= $parPage()) { '' } @else {
        <div class="w-full flex justify-end mt-4 bottom-4 right-4">
            <app-pagination
                [$pageNumber]="$currentPage()"
                [$totalItem]="50"
                [$parPage]="$parPage()"
                [$showItem]="3"
                (setPageNumber)="$currentPage.set($event)"
            ></app-pagination>
        </div>
        }
    </div>
</div>
