// client/src/views/Pagination.jsx
import {
  MdOutlineKeyboardDoubleArrowLeft,
  MdOutlineKeyboardDoubleArrowRight,
} from 'react-icons/md'

const Pagination = ({
  pageNumber,
  setPageNumber,
  totalItem,
  parPage,
  showItem,
}) => {
  let totalPage = Math.ceil(totalItem / parPage)
  let startPage = pageNumber
  let dif = totalPage - pageNumber

  if (dif <= showItem) startPage = totalPage - showItem

  let endPage = startPage < 0 ? showItem : showItem + startPage

  if (startPage <= 0) startPage = 1

  const createBtn = () => {
    const btns = []

    for (let i = startPage; i < endPage; i++) {
      console.log(i);
      btns.push(
        <li
          key={i}
          onClick={() => setPageNumber(i)}
          className={` ${
            pageNumber === i
              ? 'bg-indigo-300 shadow-lg shadow-indigo-300/50 text-white'
              : 'bg-slate-600 hover:bg-indigo-400 shadow-lg hover:shadow-indigo-500/50 hover:text-white text-[#d0d2d6]'
          } w-[33px] h-[33px] rounded-full flex justify-center items-center cursor-pointer `}
        >
          {i}
        </li>
      )
    }

    return btns
  }

  return (
    <ul className="flex gap-3">
      {pageNumber > 1 && (
        <li
          onClick={() => setPageNumber(pageNumber - 1)}
          className="w-[33px] h-[33px] rounded-full flex justify-center items-center bg-slate-300 text-[#000000] cursor-pointer"
        >
          <MdOutlineKeyboardDoubleArrowLeft />
        </li>
      )}
      {createBtn()}
      {pageNumber < totalPage && (
        <li
          onClick={() => setPageNumber(pageNumber + 1)}
          className="w-[33px] h-[33px] rounded-full flex justify-center items-center bg-slate-300 text-[#000000] cursor-pointer"
        >
          <MdOutlineKeyboardDoubleArrowRight />
        </li>
      )}
    </ul>
  )
}

export default Pagination

// client-angular/src/app/views/pagination.component.ts
import { CommonModule } from '@angular/common'
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Output,
  effect,
  input,
  signal,
} from '@angular/core'
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome'
import { faAngleLeft, faAngleRight } from '@fortawesome/free-solid-svg-icons'

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [CommonModule, FontAwesomeModule],
  template: `
    <ng-template #btns>
      <li
        class="w-[33px] h-[33px] rounded-full flex justify-center items-center cursor-pointer"
      >
        Hola
      </li>
    </ng-template>
    <div class="flex gap-3">
      @if ($pageNumber() > 1) {
      <li
        class="w-[33px] h-[33px] rounded-full flex justify-center items-center bg-slate-300 text-[#000000] cursor-pointer"
        (click)="setPageNumber.emit($pageNumber() - 1)"
        (keypress)="('')"
        tabindex="0"
      >
        <fa-icon [icon]="faAngleLeft"></fa-icon>
      </li>
      }
      <ng-container *ngTemplateOutlet="btns"></ng-container>
      @if ($pageNumber() < $totalPage()) {
      <li
        class="w-[33px] h-[33px] rounded-full flex justify-center items-center bg-slate-300 text-[#000000] cursor-pointer"
        (click)="setPageNumber.emit($pageNumber() + 1)"
        (keypress)="('')"
        tabindex="1"
      >
        <fa-icon [icon]="faAngleRight"></fa-icon>
      </li>
      }
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaginationComponent {
  /* @Input({ required: true }) pageNumber!: number;
  @Input({ required: true }) totalItem!: number;
  @Input({ required: true }) parPage!: number;
  @Input({ required: true }) showItem!: number; */
  $pageNumber = input.required<number>();
  $totalItem = input.required<number>();
  $parPage = input.required<number>();
  $showItem = input.required<number>();

  @Output() setPageNumber = new EventEmitter<number>();

  public $totalPage = signal(0);
  public $startPage = signal(0);
  public $endPage = signal(0);

  public faAngleRight = faAngleRight;
  public faAngleLeft = faAngleLeft;

  constructor() {
    effect(
      () => {
        /* console.log(
        `Los valores son: ${this.$pageNumber()}, ${this.$totalItem()}, ${this.$parPage()}, ${this.$showItem()}`
      ); */
        this.$totalPage.set(Math.ceil(this.$totalItem() / this.$parPage()));
        this.$startPage.set(this.$pageNumber());

        const dif = this.$totalPage() - this.$pageNumber();

        if (dif <= this.$showItem())
          this.$startPage.set(this.$totalPage() - this.$showItem());

        this.$endPage.set(
          this.$startPage() < 0
            ? this.$showItem()
            : this.$showItem() + this.$startPage()
        );

        if (this.$startPage() <= 0) this.$startPage.set(1);
        // console.log(`El valor de totalPage es: ${this.$totalPage()}`);
        // console.log(`El valor de startPage es: ${this.$startPage()}`);
        // console.log(`El valor de endPage es: ${this.$endPage()}`);
      },
      { allowSignalWrites: true }
    );
  }
}
