// client/src/views/auth/AdminLogin.jsx
import { useState } from 'react'
import { useDispatch } from 'react-redux'
import { adminLogin } from '../../store/reducers/authReducer'

const AdminLogin = () => {
  const dispatch = useDispatch()

  const [state, setState] = useState({
    email: '',
    password: '',
  })

  const inputHandle = (event) => {
    setState({
      ...state,
      [event.target.name]: event.target.value,
    })
  }

  const submit = (event) => {
    event.preventDefault()

    console.log(state)

    dispatch(adminLogin(state))
  }

  return (
    <div className="min-w-screen min-h-screen bg-[#cdcae9] flex justify-center items-center">
      <div className="w-[350px] text-[#ffffff] p-2">
        <div className="bg-[#6f68d1] p-4 rounded-md">
          <div className="h-[70px] flex justify-center items-center">
            <div className="w-[180px] h-[50px]">
              <img
                className="w-full h-full"
                src="http://localhost:3000/images/logo.png"
                alt="image"
              />
            </div>
          </div>
          <form onSubmit={submit}>
            <div className="flex flex-col w-full gap-1 mb-3">
              <label htmlFor="email">Email</label>
              <input
                onChange={inputHandle}
                value={state.email}
                className="px-3 py-2 outline-none border border-slate-400 bg-transparent rounded-md"
                type="email"
                name="email"
                placeholder="Email"
                id="email"
                required
              />
            </div>
            <div className="flex flex-col w-full gap-1 mb-3">
              <label htmlFor="password">Password</label>
              <input
                onChange={inputHandle}
                value={state.password}
                className="px-3 py-2 outline-none border border-slate-400 bg-transparent rounded-md"
                type="password"
                name="password"
                placeholder="Password"
                id="password"
                required
              />
            </div>
            <button className="bg-slate-800 w-full hover:shadow-blue-300/ hover:shadow-lg text-white rounded-md px-7 py-2 mb-3">
              Login
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}

export default AdminLogin

// client-angular/src/app/views/auth/admin-login.component.ts
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { FormsModule, NgForm } from '@angular/forms'

@Component({
  selector: 'app-admin-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `<div
    class="min-w-screen min-h-screen bg-[#cdcae9] flex justify-center items-center"
  >
    <div class="w-[350px] text-[#ffffff] p-2">
      <div class="bg-[#6f68d1] p-4 rounded-md">
        <div class="h-[70px] flex justify-center items-center">
          <div class="w-[180px] h-[50px]">
            <img class="w-full h-full" src="images/logo.png" alt="image" />
          </div>
        </div>
        <form #adminLoginForm="ngForm" (ngSubmit)="submit(adminLoginForm)">
          <div class="flex flex-col w-full gap-1 mb-3">
            <label for="email">Email</label>
            <input
              class="px-3 py-2 outline-none border border-slate-400 bg-transparent rounded-md"
              type="email"
              name="email"
              placeholder="Email"
              id="email"
              ngModel
              required
              email
            />
          </div>
          <div class="flex flex-col w-full gap-1 mb-3">
            <label for="password">Password</label>
            <input
              class="px-3 py-2 outline-none border border-slate-400 bg-transparent rounded-md"
              type="password"
              name="password"
              placeholder="Password"
              id="password"
              ngModel
              required
              pattern=".{10,}"
            />
          </div>
          <button
            type="submit"
            class="bg-slate-800 w-full hover:shadow-blue-300/ hover:shadow-lg text-white rounded-md px-7 py-2 mb-3"
          >
            Login
          </button>
        </form>
      </div>
    </div>
  </div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AdminLoginComponent {
  public submit(form: NgForm): void {
    console.log(form);
  }
}
