// client-angular/src/app/views/admin/category.component.ts
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component } from '@angular/core'

@Component({
  selector: 'app-category',
  standalone: true,
  imports: [
    CommonModule,
  ],
  templateUrl: './category.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CategoryComponent { }

<div class="px-2 lg:px-7 pt-5">
    <div
        class="flex lg:hidden justify-between items-center mb-5 p-4 bg-[#6a5fdf] rounded-md"
    >
        <h1 class="text-[#d0d2d6] font-semibold text-lg">Category</h1>
        <button
            (click)="$show.set(true)"
            class="bg-red-500 shadow-lg hover:shadow-red-500/40 px-4 py-2 cursor-pointer text-white rounded-sm text-sm"
        >
            Add
        </button>
    </div>
    <div class="flex flex-wrap w-full">
        <div class="w-full lg:w-7/12">
            <div class="w-full p-4 bg-[#6a5fdf] rounded-md">
                <app-search
                    [searchValue]="$searchValue()"
                    (setSearchValue)="$searchValue.set($event)"
                    (setParPage)="$parPage.set($event)"
                ></app-search>
                <div class="relative overflow-x-auto">
                    <table class="w-full text-sm text-left text-[#d0d2d6]">
                        <thead
                            class="text-sm text-[#d0d2d6] uppercase border-b border-slate-700"
                        >
                            <tr>
                                <th scope="col" class="py-3 px-4">No</th>
                                <th scope="col" class="py-3 px-4">Image</th>
                                <th scope="col" class="py-3 px-4">Name</th>
                                <th scope="col" class="py-3 px-4">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (category of $categories(); track category._id;
                            let idx = $index) {
                            <tr>
                                <td
                                    class="py-1 px-4 font-medium whitespace-nowrap"
                                >
                                    {{ idx + 1 }}
                                </td>
                                <td
                                    class="py-1 px-4 font-medium whitespace-nowrap"
                                >
                                    <img
                                        class="w-[45px] h-[45px]"
                                        [src]="category.image"
                                        alt=""
                                    />
                                </td>
                                <td
                                    class="py-1 px-4 font-medium whitespace-nowrap"
                                >
                                    {{ category.name }}
                                </td>
                                <td
                                    class="py-1 px-4 font-medium whitespace-nowrap"
                                >
                                    <div
                                        class="flex justify-start items-center gap-4"
                                    >
                                        <a
                                            class="p-[6px] bg-yellow-500 rounded hover:shadow-lg hover:shadow-yellow-500/50"
                                        >
                                            <fa-icon
                                                [icon]="fanPenToSquare"
                                            ></fa-icon>
                                        </a>
                                        <a
                                            class="p-[6px] bg-red-500 rounded hover:shadow-lg hover:shadow-red-500/50"
                                        >
                                            <fa-icon [icon]="faTrash"></fa-icon>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="w-full flex justify-end mt-4 bottom-4 right-4">
                    <app-pagination
                        [$pageNumber]="$currentPage()"
                        [$totalItem]="50"
                        [$parPage]="$parPage()"
                        [$showItem]="3"
                        (setPageNumber)="$currentPage.set($event)"
                    ></app-pagination>
                </div>
            </div>
        </div>
        <div
            class="w-[320px] lg:w-5/12 translate-x-100 lg:relative lg:right-0 fixed z-[9999] top-0 transition-all duration-500"
            [ngClass]="$show() ? 'right-0' : '-right-[340px]'"
        >
            <div class="w-full pl-5">
                <div
                    class="bg-[#6a5fdf] h-screen lg:h-auto px-3 py-2 lg:rounded-md text-[#d0d2d6]"
                >
                    <div class="flex justify-between items-center mb-4">
                        <h1
                            class="text-[#d0d2d6] font-semibold text-xl mb-4 w-full text-center"
                        >
                            Add Category
                        </h1>
                        <div class="block lg:hidden">
                            <fa-icon [icon]="faCircleXmark"></fa-icon>
                        </div>
                    </div>
                    <form [formGroup]="categoryForm" (ngSubmit)="submit()">
                        <div class="flex flex-col w-full gap-1 mb-3">
                            <label for="name"> Category Name</label>
                            <input
                                class="px-4 py-2 focus:border-indigo-500 outline-none bg-[#ffffff] border border-slate-700 rounded-md text-[#000000]"
                                type="text"
                                id="name"
                                name="category_name"
                                placeholder="Category Name"
                            />
                        </div>
                        <div>
                            <label
                                class="flex justify-center items-center flex-col h-[238px] cursor-pointer border border-dashed hover:border-red-500 w-full border-[#d0d2d6]"
                                for="image"
                            >
                            </label>
                            <input
                                class="hidden"
                                type="file"
                                name="image"
                                id="image"
                            />
                            <div class="mt-4">
                                <button
                                    [disabled]="$loader() ? true : false"
                                    class="bg-red-800 w-full hover:shadow-red-300/50 hover:shadow-lg text-white rounded-md px-7 py-2 mb-3"
                                >
                                    Add Category
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

// client/src/views/admin/Category.jsx
import { useState } from 'react'
import { FaEdit, FaImage, FaTrash } from 'react-icons/fa'
import { IoMdCloseCircle } from "react-icons/io"
import { Link } from 'react-router-dom'
import Pagination from '../Pagination'

const Category = () => {
  const [currentPage, setCurrentPage] = useState(1)
  // const [searchValue, setSearchValue] = useState('')
  const [parPage, setParPage] = useState(5)
  const [show, setShow] = useState(false)

  return (
    <div className="px-2 lg:px-7 pt-5">
      <div className="flex lg:hidden justify-between items-center mb-5 p-4 bg-[#6a5fdf] rounded-md">
        <h1 className="text-[#d0d2d6] font-semibold text-lg">Category</h1>
        <button
          onClick={() => setShow(true)}
          className="bg-red-500 shadow-lg hover:shadow-red-500/40 px-4 py-2 cursor-pointer text-white rounded-sm text-sm"
        >
          Add
        </button>
      </div>
      <div className="flex flex-wrap w-full">
        <div className="w-full lg:w-7/12">
          <div className="w-full p-4 bg-[#6a5fdf] rounded-md">
            <div className="flex justify-between items-center">
              <select
                onChange={(e) => setParPage(parseInt(e.target.value))}
                className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
              >
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="20">20</option>
              </select>
              <input
                className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#6a5fdf] border border-slate-700 rounded-md text-[#d0d2d6]"
                type="text"
                placeholder="search"
              />
            </div>
            <div className="relative overflow-x-auto">
              <table className="w-full text-sm text-left text-[#d0d2d6]">
                <thead className="text-sm text-[#d0d2d6] uppercase border-b border-slate-700">
                  <tr>
                    <th scope="col" className="py-3 px-4">
                      No
                    </th>
                    <th scope="col" className="py-3 px-4">
                      Image
                    </th>
                    <th scope="col" className="py-3 px-4">
                      Name
                    </th>
                    <th scope="col" className="py-3 px-4">
                      Action
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {[1, 2, 3, 4, 5].map((d, i) => (
                    <tr key={i}>
                      <td
                        scope="row"
                        className="py-1 px-4 font-medium whitespace-nowrap"
                      >
                        {d}
                      </td>
                      <td
                        scope="row"
                        className="py-1 px-4 font-medium whitespace-nowrap"
                      >
                        <img
                          className="w-[45px] h-[45px]"
                          src={`http://localhost:3000/images/category/${d}.jpg`}
                          alt=""
                        />
                      </td>
                      <td
                        scope="row"
                        className="py-1 px-4 font-medium whitespace-nowrap"
                      >
                        Tshirt
                      </td>
                      <td
                        scope="row"
                        className="py-1 px-4 font-medium whitespace-nowrap"
                      >
                        <div className="flex justify-start items-center gap-4">
                          <Link className="p-[6px] bg-yellow-500 rounded hover:shadow-lg hover:shadow-yellow-500/50">
                            {' '}
                            <FaEdit />{' '}
                          </Link>
                          <Link className="p-[6px] bg-red-500 rounded hover:shadow-lg hover:shadow-red-500/50">
                            {' '}
                            <FaTrash />{' '}
                          </Link>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="w-full flex justify-end mt-4 bottom-4 right-4">
              <Pagination
                pageNumber={currentPage}
                setPageNumber={setCurrentPage}
                totalItem={50}
                parPage={parPage}
                showItem={3}
              />
            </div>
          </div>
        </div>
        <div
          className={`w-[320px] lg:w-5/12 translate-x-100 lg:relative lg:right-0 fixed ${
            show ? 'right-0' : '-right-[340px]'
          } z-[9999] top-0 transition-all duration-500 `}
        >
          <div className="w-full pl-5">
            <div className="bg-[#6a5fdf] h-screen lg:h-auto px-3 py-2 lg:rounded-md text-[#d0d2d6]">
              <div className="flex justify-between items-center mb-4">
                <h1 className="text-[#d0d2d6] font-semibold text-xl mb-4 w-full text-center ">
                  Add Category
                </h1>

                <div onClick={() => setShow(false)} className="block lg:hidden">
                  <IoMdCloseCircle />
                </div>
              </div>
              <form>
                <div className="flex flex-col w-full gap-1 mb-3">
                  <label htmlFor="name"> Category Name</label>
                  <input
                    className="px-4 py-2 focus:border-indigo-500 outline-none bg-[#ffffff] border border-slate-700 rounded-md text-[#000000]"
                    type="text"
                    id="name"
                    name="category_name"
                    placeholder="Category Name"
                  />
                </div>
                <div>
                  <label
                    className="flex justify-center items-center flex-col h-[238px] cursor-pointer border border-dashed hover:border-red-500 w-full border-[#d0d2d6]"
                    htmlFor="image"
                  >
                    <span>
                      <FaImage />{' '}
                    </span>
                    <span>Select Image</span>
                  </label>
                  <input
                    className="hidden"
                    type="file"
                    name="image"
                    id="image"
                  />
                  <div>
                    <button className="bg-red-500 w-full hover:shadow-red-500/40 hover:shadow-md text-white rounded-md px-7 py-2 my-2">
                      Add Category
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Category
